#!/usr/bin/env python3
"""Generate a one-time SQL seed migration for public.highway_junctions
from a saariko/RoadsKMs junctions.csv snapshot.

RoadsKMs packs aliases into the same name_he/name_en string, " / "-delimited
(e.g. "צומת בן גוריון מערב / נתבג / חבד / כפר חבד"). This splits each row's
name into a canonical name (segment 0) + an alias array (remaining segments),
matching the highway_junctions schema (see supabase/migrations/20260908150000_highway_junctions.sql).

This is a ONE-TIME import, not a sync — run once, review the generated
migration, commit it. Re-running against a newer RoadsKMs snapshot after the
table already has manual edits would need real reconciliation logic this
script does not implement (see docs/locations-and-mapping.md §4).
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path


def split_name(raw: str) -> tuple[str, list[str]]:
    """"A / B / C" -> ("A", ["B", "C"]). Single name -> (name, [])."""
    parts = [p.strip() for p in raw.split(' / ') if p.strip()]
    if not parts:
        return '', []
    return parts[0], parts[1:]


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_text_array(values: list[str]) -> str:
    if not values:
        return "'{}'"
    return "array[" + ", ".join(sql_quote(v) for v in values) + "]"


def sql_nullable_text(value: str) -> str:
    return sql_quote(value) if value else 'null'


def validate_split(rows: list[dict[str, str]]) -> int:
    """Print a warning for any row whose split looks suspicious, before trusting
    it over all rows sight-unseen — the source data is hand-curated, not
    guaranteed-consistent (docs/locations-and-mapping.md §4 provenance note).

    Returns the number of rows whose canonical name_he collides with another
    row's — these silently lose all but the first occurrence to the
    generated `on conflict (name_he) do nothing`, since name_he is unique.
    When this script was last run, all such collisions were confirmed (by
    haversine distance, by hand) to be near-duplicate points of the same
    physical interchange, not distinct junctions — re-verify that assumption
    before trusting a nonzero count here on a future run."""
    seen: dict[str, dict[str, str]] = {}
    collisions = 0
    for row in rows:
        name_he, aliases_he = split_name(row['name_he'])
        if not name_he:
            print(f"WARNING: empty canonical name_he for row: {row!r}", file=sys.stderr)
        if any(len(a) > 40 for a in aliases_he):
            print(f"WARNING: suspiciously long alias in: {row['name_he']!r}", file=sys.stderr)
        if aliases_he and len(aliases_he) > 5:
            print(f"WARNING: unusually many aliases ({len(aliases_he)}) in: {row['name_he']!r}", file=sys.stderr)
        if name_he in seen:
            collisions += 1
            print(
                f"NOTE: canonical name_he collision, only the first occurrence survives "
                f"'on conflict do nothing': {name_he!r} at ({row['lat']}, {row['lon']}) "
                f"vs. earlier ({seen[name_he]['lat']}, {seen[name_he]['lon']})",
                file=sys.stderr,
            )
        else:
            seen[name_he] = row
    return collisions


def build_insert_values(rows: list[dict[str, str]]) -> list[str]:
    lines = []
    for row in rows:
        name_he, aliases_he = split_name(row['name_he'])
        name_en, aliases_en = split_name(row.get('name_en', ''))
        lines.append(
            "  ({name_he}, {name_en}, {aliases_he}, {aliases_en}, {roads}, {lat}, {lng})".format(
                name_he=sql_quote(name_he),
                name_en=sql_nullable_text(name_en),
                aliases_he=sql_text_array(aliases_he),
                aliases_en=sql_text_array(aliases_en),
                roads=sql_nullable_text(row.get('roads', '').strip()),
                lat=float(row['lat']),
                lng=float(row['lon']),
            )
        )
    return lines


def main() -> None:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else 'scripts/data/roadskms-junctions.csv')
    out = Path(
        sys.argv[2]
        if len(sys.argv) > 2
        else 'supabase/migrations/20260908150200_seed_highway_junctions.sql'
    )
    with src.open(encoding='utf-8') as f:
        rows = list(csv.DictReader(f))

    collisions = validate_split(rows)
    values = build_insert_values(rows)
    sql = (
        "-- One-time seed from saariko/RoadsKMs junctions.csv "
        f"({len(rows)} rows). Generated by scripts/import-highway-junctions.py — do not re-run\n"
        "-- against a newer snapshot without reconciling manual edits (docs/locations-and-mapping.md §4).\n\n"
        "insert into public.highway_junctions (name_he, name_en, aliases_he, aliases_en, roads, lat, lng)\nvalues\n"
        + ",\n".join(values)
        + "\non conflict (name_he) do nothing;\n"
    )
    out.write_text(sql, encoding='utf-8')
    landed = len(rows) - collisions
    print(f"wrote {len(rows)} rows to {out} — {landed} distinct junctions will land ({collisions} name_he collisions dropped by on conflict)")


if __name__ == '__main__':
    main()
